repos:
    - repo: local
      hooks:
        - id: pre-commit
          name: pre-commit
          entry: bash pre_commit.sh
          language: system
          verbose: true
          require_serial: true
        