repos:
    - repo: local
      hooks:
      - id: run-pre-commit-check
        name: run-pre-commit-check
        entry: bash pre_commit_check.sh
        language: system
        require_serial: True
        verbose: True